### ISSUE TITLE
Todo App 요구명세서 작성

### ISSUE THREAD

**Issue by tjddmssl** [tjddmssl/TodoList#1]
### 만들고자 하는 기능이 무엇인가요?
Todo app의 CRUD 기능, 간단한 json서버 구현하여 데이터 받아오기

### 해당기능을 구현하기 위해 할일
- [ ] 컴포넌트 별로 나눠서 기능을 어떻게 추가할지 계획
- [ ] CRUD 기능 구현
- [ ] Styled-Component활용해서 css작성, 관리
- [ ] json 서버 만들기, post man으로 확인
- [ ] 각 컴포넌트마다 필요한 json server data를 feath로 GET,POST,DELETE,PATCH 메서드를 사용하여 활용하기
- [ ] 번들과 깃허브로 배포하기
